name: Actions Workflow

on: [push, pull_req]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:  
      - name: Simple JS Actions
        run: |
          pwd
          ls -a
      - name: Checkout
        uses: actions/checkout@v1
      - name: Simple JS Actions
        run: |
          pwd
          node -v