name: Shell commands

on: [push]

jobs:
  run-sell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: run a command
        run: pwd
      - name: run py command
        run: |
          import platform
          print (platform.processor())
        shell: python